host = 127.0.0.1
port = 6600
log = /home/jonny/.config/mpdscribble/mpdscribble.log          
verbose = 1

[last.fm]
url = http://post.audioscrobbler.com/
username = 
password = 
journal = /home/jonny/.config/mpdscribble/lastfm.journal
